name: Test
on: [ workflow_dispatch ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ fromJson('package.json').version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: echo $VERSION
